#!/usr/bin/env python3
import os
import glob
from PIL import Image

size = 128, 128

for file in glob.glob("/home/student-03-37094d2e364e/images/ic_*"):
  print(os.path.basename(file))
  im = Image.open(file).convert('RGB')
  im.rotate(-90).resize((size)).save("/opt/icons/" + os.path.basename(file), "JPEG")
