#!/usr/bin/env python3
import requests
import os

path = "/home/student-04-8509cc2bbce2/supplier-data/images/"
dirs = os.listdir( path )
url = "http://localhost/upload/"

for item in dirs:
        print(path + '/' + item)
        with open(path + '/' + item, 'rb') as opened:
                r = requests.post(url, files={'file': opened})

